# Generated by Django 6.0 on 2026-07-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('memory', '0013_message_is_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('self_declared', 'Dit qui il/elle est'), ('passive_inference', 'Deduit passivement'), ('shared_memory', 'Sait quelque chose que seul X sait'), ('vouched', "Presente par quelqu'un de confiance"), ('authenticated', 'Prouve par le transport'), ('contradicted', "S'est trompe sur un fait partage"), ('denied', 'Nie etre cette personne'), ('revoked', 'Mika ne le croit plus')], default='self_declared', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('rejected', 'Rejetee')], default='pending', max_length=15)),
                ('evidence', models.TextField(blank=True, default='')),
                ('channel', models.CharField(blank=True, default='', max_length=50)),
                ('trust', models.CharField(default='public', max_length=20)),
                ('applied_weight', models.FloatField(default=0.0)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='identity',
            name='binding_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='identity',
            name='bound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='bound_via',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='identity',
            name='certainty',
            field=models.FloatField(default=0.0, help_text='0..1 — how sure Mika is this identity is the linked entity'),
        ),
        migrations.AddField(
            model_name='identityhandle',
            name='is_ephemeral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identityhandle',
            name='trust',
            field=models.CharField(default='public', help_text='ChannelTrust value: authenticated | account | public | internal', max_length=20),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['-certainty'], name='identity_id_certain_2930ef_idx'),
        ),
        migrations.AddIndex(
            model_name='identityhandle',
            index=models.Index(fields=['is_ephemeral', 'last_seen'], name='identity_id_is_ephe_633783_idx'),
        ),
        migrations.AddField(
            model_name='identityclaim',
            name='handle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='identity.identityhandle'),
        ),
        migrations.AddField(
            model_name='identityclaim',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='identity.identity'),
        ),
        migrations.AddIndex(
            model_name='identityclaim',
            index=models.Index(fields=['status', '-created_at'], name='identity_id_status_d64c25_idx'),
        ),
        migrations.AddIndex(
            model_name='identityclaim',
            index=models.Index(fields=['identity', 'status'], name='identity_id_identit_4be2c7_idx'),
        ),
    ]
