# Generated by Django 5.2.1 on 2026-04-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField(blank=True, default='')),
                ('raw_response', models.TextField(blank=True, default='')),
                ('parsed_output', models.JSONField(blank=True, null=True)),
                ('outcome', models.CharField(default='ok', max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_pr_project_382eee_idx')],
            },
        ),
    ]
