# Generated by Django 6.1.1 on 2026-09-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRunReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_reservations', to='projects.project')),
            ],
        ),
    ]
