# Generated by Django 5.2.1 on 2026-04-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0011_dailyjournal_dream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('origin', models.CharField(choices=[('user', 'User-confided'), ('self', 'Self-initiated')], default='user', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('tone_directive', models.TextField(blank=True, default='', help_text="How to write/respond while working on this project (e.g. 'Langage soutenu, factuel, pas d'abréviations').")),
                ('emotion_policy', models.CharField(choices=[('off', 'No emotions (neutral professional)'), ('muted', 'Muted (emotions allowed but dampened)'), ('full', 'Full emotional expression')], default='off', help_text="Emotional layer to apply during project work. Default 'off'.", max_length=10)),
                ('instructions', models.JSONField(blank=True, default=list, help_text="List of positive directives. e.g. ['Toujours demander accord avant envoi']")),
                ('out_of_scope', models.JSONField(blank=True, default=list, help_text='Explicit no-go topics/actions for this project.')),
                ('requires_approval', models.BooleanField(default=False, help_text='When True, any action with side-effects queues as ProjectPendingAction instead of executing immediately.')),
                ('allowed_modules', models.JSONField(blank=True, default=list, help_text="Module names the ProjectRunner may invoke (e.g. ['email', 'files']). Empty = no tools at all.")),
                ('resource_paths', models.JSONField(blank=True, default=list, help_text='Filesystem / logical paths relevant to this project.')),
                ('contacts', models.JSONField(blank=True, default=list, help_text='Email addresses / handles in scope for this project.')),
                ('schedule_rule', models.CharField(blank=True, default='', help_text="When the runner should advance the project. Supported forms:\n  ''                 (manual only — advance via admin or user msg)\n  'interval:5m'      (every 5 minutes; s/m/h units)\n  'cron:0 9 * * MON-FRI' (cron expression)\n  'idle:30m'         (when Mika idle for >= 30 minutes)\n  'event:email.new'  (reacted to a module event)\n", max_length=120)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('runs_since_user_input', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'person'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='memory.entity')),
            ],
            options={
                'ordering': ['-priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=15)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField(help_text='Human-readable description of what Mika wants to do.')),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('failed', 'Failed to execute')], default='pending', max_length=10)),
                ('user_note', models.TextField(blank=True, default='', help_text='Optional note from the user on approve/reject.')),
                ('execution_result', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('advanced', 'Advanced (one tick done)'), ('waited', 'Waited (no tick needed)'), ('reported', 'Reported to user'), ('blocked', 'Blocked'), ('awaiting_approval', 'Awaiting user approval'), ('error', 'Error during run')], max_length=20)),
                ('summary', models.TextField()),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='projects.projecttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-priority'], name='projects_pr_status_e5abda_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'next_run_at'], name='projects_pr_status_34b836_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status', 'order'], name='projects_pr_project_0bd80b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpendingaction',
            index=models.Index(fields=['status', '-created_at'], name='projects_pr_status_4f4a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpendingaction',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_77a830_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlog',
            index=models.Index(fields=['project', '-created_at'], name='projects_pr_project_fdc85d_idx'),
        ),
    ]
