# Generated by Django 6.0 on 2026-08-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_monthly_token_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_command',
            field=models.CharField(blank=True, default='', help_text="Commande lancée par l'outil project_test, par exemple 'pytest -q'. Vide = l'outil demande la commande à chaque fois.", max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource_paths',
            field=models.JSONField(blank=True, default=list, help_text="Chemins EXTÉRIEURS à l'atelier que ce projet peut consulter, en plus de sa propre racine. Le travail lui-même vit dans data/projects/<id>-<slug>/ ; ce champ sert à pointer une source de référence qu'on ne veut pas recopier."),
        ),
    ]
