# Generated by Django 6.0 on 2026-04-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_emailaccount_last_fetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RSSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('published', models.CharField(blank=True, default='', max_length=100)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='modules.rssfeed')),
            ],
            options={
                'ordering': ['-seen_at'],
                'unique_together': {('feed', 'entry_hash')},
            },
        ),
    ]
