# Generated by Django 6.0 on 2026-04-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0002_consolidationlog_theme_message_emotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConscienceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_count', models.IntegerField(default=0)),
                ('max_pertinence', models.FloatField(default=0.0)),
                ('global_mood', models.CharField(blank=True, default='', max_length=30)),
                ('global_intensity', models.FloatField(default=0.0)),
                ('idle_seconds', models.IntegerField(default=0)),
                ('decision', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('memory_actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('raw_data', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('emotional', 'Emotional'), ('memory', 'Memory'), ('temporal', 'Temporal'), ('external', 'External'), ('system', 'System')], default='system', max_length=30)),
                ('pertinence', models.FloatField(default=0.5)),
                ('emotional_reaction', models.CharField(blank=True, default='', max_length=30)),
                ('emotional_intensity', models.FloatField(default=0.0)),
                ('acted_upon', models.BooleanField(default=False)),
                ('action_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('souvenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='memory.souvenir')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'acted_upon'], name='conscience__created_3d4b82_idx'), models.Index(fields=['category', '-pertinence'], name='conscience__categor_7868ec_idx')],
            },
        ),
    ]
