# Generated by Django 6.0 on 2026-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0001_initial'),
        ('memory', '0004_connaissance_memory_conn_is_vali_53281a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acted', 'Acted'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['status', '-created_at'], name='conscience__status_68d724_idx'),
        ),
    ]
