# Generated by Django 5.2.1 on 2026-04-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0005_remove_acted_upon'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rumination',
            new_name='conscience__status_187012_idx',
            old_name='conscience__status_8a2f11_idx',
        ),
    ]
