# Generated by Django 6.0 on 2026-08-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0007_rumination_decayed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consciencelog',
            name='trousse',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
