# Generated by Django 6.0 on 2026-08-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0010_journal_et_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledaction',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='travail',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
