# Generated by Django 6.0 on 2026-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0011_trousse_persistee'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='reprendre_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
