# Generated by Django 6.0 on 2026-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0012_attente_avec_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
