# Generated by Django 6.1.1 on 2026-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0018_rumination_reflechie_le'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consciencelog',
            index=models.Index(fields=['decision', '-created_at'], name='conscience__decisio_aa546a_idx'),
        ),
        migrations.AddIndex(
            model_name='consciencelog',
            index=models.Index(fields=['-created_at'], name='conscience__created_c5a6d5_idx'),
        ),
    ]
