# Generated by Django 6.0.2 on 2026-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='RFC Message-ID header for deduplication', max_length=500, unique=True)),
                ('uid', models.CharField(blank=True, default='', max_length=100)),
                ('from_addr', models.CharField(max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('body_preview', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
