# Generated by Django 6.0.2 on 2026-02-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_processedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('emails_received', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='RFC Message-ID header for deduplication', max_length=500)),
                ('uid', models.CharField(blank=True, default='', max_length=100)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500)),
                ('references', models.TextField(blank=True, default='')),
                ('from_address', models.CharField(max_length=500)),
                ('to_addresses', models.TextField(help_text='Comma-separated')),
                ('cc_addresses', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('has_attachments', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-email_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g. 'Gmail Perso')", max_length=100)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_user', models.CharField(max_length=255)),
                ('imap_password', models.CharField(max_length=255)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedEmail',
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='modules.emailaccount'),
        ),
        migrations.AddField(
            model_name='contact',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='modules.emailaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('account', 'message_id')},
        ),
    ]
