# Generated by Django 6.0.2 on 2026-02-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_contact_email_emailaccount_delete_processedemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='initial_sync_done',
            field=models.BooleanField(default=False, help_text='Whether the first email sync has completed (replies disabled until then)'),
        ),
    ]
