# Generated by Django 6.0.2 on 2026-02-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_emailaccount_initial_sync_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='last_fetch',
            field=models.DateTimeField(blank=True, help_text='Last successful IMAP fetch', null=True),
        ),
    ]
