# Generated by Django 5.2.1 on 2026-04-13 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_rssfeed_rssentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='Taille décodée en octets')),
                ('disk_path', models.CharField(help_text='Chemin absolu sur le disque', max_length=500)),
                ('person_id', models.CharField(default='anonymous', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
