# Generated by Django 6.0 on 2026-05-30 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0005_emotionalsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to='memory.entity')),
            ],
            options={
                'verbose_name_plural': 'identities',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='IdentityHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('person_id', models.CharField(db_index=True, max_length=100)),
                ('kind', models.CharField(choices=[('consumer', 'Consumer'), ('module', 'Module')], default='module', max_length=20)),
                ('delivery_ref', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='identity.identity')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['entity'], name='identity_id_entity__a3de3b_idx'),
        ),
        migrations.AddIndex(
            model_name='identityhandle',
            index=models.Index(fields=['person_id'], name='identity_id_person__93ac4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='identityhandle',
            unique_together={('channel', 'person_id')},
        ),
    ]
