"""Context assembly — gather all contextual information for a conversation turn.

Collects memory, emotion, module context, and conversation history
into a single structure ready for the AI call.
"""

import logging
from dataclasses import dataclass, field

from drives.engine import drive_engine
from emotion.engine import emotion_engine
from identity.resolver import identity_resolver
from identity.trust import is_internal_person
from memory.manager import memory_manager
from modules.manager import module_manager

logger = logging.getLogger(__name__)


@dataclass
class ConversationContext:
    """All context assembled for a single conversation turn.

    Every field has a default, so ``ConversationContext()`` is a valid empty
    context. That is not laxity: an absent layer and an empty layer mean the
    same thing to ``build_system_prompt`` (skip the block), and requiring six
    of them positionally only forced every caller and test to spell out
    ``memory_context="", tools=[], ...`` to say nothing.
    """
    memory_context: str = ""
    emotion_context: str = ""
    module_context: str = ""
    history: list[dict] = field(default_factory=list)
    # Generic tool list (provider-agnostic ``ModuleTool``); the provider
    # translates to its native tool protocol (MCP, function-calling, …).
    tools: list = field(default_factory=list)
    tool_names: list[str] = field(default_factory=list)
    # Self-concept: evolving autobiographical paragraph, regenerated by
    # the consolidator. Empty string if no narrative has been produced yet.
    self_concept: str = ""
    # Theory of mind: what Mika knows/assumes about the current person,
    # plus her pending commitments toward them. Empty if no profile
    # exists yet for this person_id.
    person_context: str = ""
    # Circadian state — current phase + energy level description, nudges
    # Mika's tone to match the time of day.
    circadian_context: str = ""
    # Fatigue/cognitive fog — when energy is low, Mika's thoughts blur.
    # Shapes TONE (not just the act/wait threshold).
    fatigue_fog: str = ""
    # Active ruminations — unresolved pertinent thoughts still on her mind.
    # Was previously surfaced only inside _act(); now visible every turn.
    rumination_context: str = ""
    # Best-effort heuristic read of the user's emotional tone (caps, emojis,
    # length, keywords). Gives Mika something to react to, not just declare.
    user_mood_hint: str = ""
    # The morning-after residue of a vivid dream from last night, if any.
    # Only injected until early afternoon and only for non-internal persons,
    # so Mika can spontaneously mention it in the first few conversations.
    dream_context: str = ""
    # Yesterday's journal — the narrative thread of the previous day, so
    # "hier" is something Mika actually remembers as a day, not just as
    # disconnected souvenirs surfaced by semantic luck.
    journal_context: str = ""
    # Project layer — set when an active Project matches the current turn
    # (user talked about it, owner mentioned, keyword hit). The string is
    # injected as `--- PROJET EN COURS ---`; the boolean forces the
    # personality prompt into "professional mode" (no emotion tag, no
    # variability block) when the matched project's emotion_policy=OFF.
    project_context: str = ""
    project_suppresses_emotion: bool = False
    # ID of the matched project — not injected in the prompt, but passed
    # through so the processor can tag outgoing side effects / skip the
    # emotion impulse when the project is "off".
    project_id: int | None = None
    # Who Mika thinks she is talking to and how sure she is — injected as
    # `--- QUI TU AS EN FACE ---`. Also gates `person_context`: below the
    # disclosure threshold, private per-person memory is withheld entirely.
    identity_context: str = ""


async def gather_context(
    message: str,
    person_id: str,
    include_tools: bool = True,
    channel: str = "",
    authenticated: bool = False,
    is_public: bool = False,
) -> ConversationContext:
    """Assemble all context needed for an AI conversation turn.

    Args:
        message: The user/trigger message (used for memory retrieval).
        person_id: Who is talking (for emotion + memory boosting).
        include_tools: Whether to include MCP tools from modules.
        channel: Transport the turn arrived on ("web", "telegram", …), used
            to decide how much the channel itself proves about the sender.
        authenticated: The transport verified this session's credentials.
        is_public: The turn happened in a shared room, not a 1:1 exchange.
    """
    # Memory context (graceful degradation)
    try:
        memory_context = await memory_manager.get_memory_context(
            message, person_id=person_id
        )
    except Exception:
        logger.warning("Memory retrieval failed, continuing without context")
        memory_context = ""

    # Self-concept: latest autobiographical narrative from the consolidator.
    # Best-effort — if the table hasn't been populated yet (no narrative
    # generated), we just skip it and the prompt uses personality alone.
    self_concept = await _fetch_self_concept()

    # Who is on the other end, and how sure Mika is. Resolved once here and
    # reused below: it decides both what the prompt says about them and
    # whether their private history may be surfaced at all.
    identity_ctx = await identity_resolver.resolve_context(
        person_id, channel=channel,
        authenticated=authenticated, is_public=is_public,
    )
    identity_context = _format_identity_block(identity_ctx)

    # Theory of mind: profile + pending commitments for the current person.
    # Gated on identity certainty — recounting what someone confided to a
    # visitor who merely *claims* to be them is the failure mode this whole
    # layer exists to prevent.
    person_context = await _fetch_person_context(identity_ctx)

    # Circadian: where Mika sits in her daily rhythm.
    circadian_context = _fetch_circadian_context()

    # Emotion context = Mika's global mood only. The per-person affective
    # stance is relational and belongs to person_context (see below), so
    # the prompt cleanly separates "how Mika feels" from "how Mika feels
    # about this person".
    emotion_context = emotion_engine.get_global_mood_context()

    # Intrinsic drives — still Mika-centric (curiosity / social need / rest),
    # so they attach to the global mood layer.
    # NOTE: drive satisfaction is triggered by conscience.observe() when the
    # chat.message event bubbles up, so we deliberately don't call
    # drive_engine.on_conversation() here to avoid double-counting.
    drive_context = drive_engine.get_context()
    if drive_context:
        emotion_context = (
            f"{emotion_context}\n{drive_context}" if emotion_context else drive_context
        )

    # Module context for system prompt (scoped to this person)
    module_context = module_manager.collect_context(person_id)

    # Conversation history
    history = memory_manager.get_conversation_context()

    # Fatigue fog — when energy is low, shape the cognitive tone
    fatigue_fog = _fatigue_fog_context()

    # Active ruminations — now visible every turn, not only during _act()
    rumination_context = await _fetch_rumination_context()

    # User mood heuristic — a best-effort read of the user's emotional
    # tone from the raw message. Skipped for internal triggers (messages
    # Mika sent herself — she doesn't "read" her own rumination).
    if is_internal_person(person_id):
        user_mood_hint = ""
    else:
        user_mood_hint = detect_user_mood_hint(message)

    # Dream residue from last night. Only surfaces in the morning and
    # only to real interlocutors (not to Mika's own conscience trigger).
    if is_internal_person(person_id):
        dream_context = ""
        journal_context = ""
    else:
        dream_context = await _fetch_dream_context()
        journal_context = await _fetch_journal_context()

    # Project detection — is this turn about an active project?
    # Skipped for internal triggers (conscience prompts don't reference
    # user-confided projects by mistake).
    project_context = ""
    project_suppresses_emotion = False
    project_id: int | None = None
    if not is_internal_person(person_id):
        try:
            from projects.detection import (
                detect_project_for_message,
                load_project_for_prompt,
            )
            match = await detect_project_for_message(message, person_id=person_id)
            if match:
                data = await load_project_for_prompt(match.project_id)
                if data:
                    project_context = _format_project_block(data)
                    project_suppresses_emotion = (data["emotion_policy"] == "off")
                    project_id = data["id"]
        except Exception:
            logger.debug("Project detection failed", exc_info=True)

    # Tools (generic ModuleTool list — the provider does the translation)
    tools: list = []
    tool_names: list[str] = []
    if include_tools:
        tools = module_manager.collect_tools()
        tool_names = [t.name for t in tools]

    return ConversationContext(
        memory_context=memory_context,
        emotion_context=emotion_context,
        module_context=module_context,
        history=history,
        tools=tools,
        tool_names=tool_names,
        self_concept=self_concept,
        person_context=person_context,
        circadian_context=circadian_context,
        fatigue_fog=fatigue_fog,
        rumination_context=rumination_context,
        user_mood_hint=user_mood_hint,
        dream_context=dream_context,
        journal_context=journal_context,
        project_context=project_context,
        project_suppresses_emotion=project_suppresses_emotion,
        project_id=project_id,
        identity_context=identity_context,
    )


def _format_identity_block(ctx) -> str:
    """Render the identity situation as the `--- QUI TU AS EN FACE ---` body.

    Silent for internal person_ids (Mika's own conscience triggers don't need
    to be told who they are) and silent when an authenticated session made
    the question moot *and* nothing is pending — in that case the person
    context block already names them, and a paragraph explaining that she is
    certain would only invite the model to talk about certainty.
    """
    if ctx.is_internal:
        return ""

    lines = [ctx.description] if ctx.description else []

    if ctx.pending_claims:
        lines.append("")
        for claim in ctx.pending_claims:
            lines.append(
                f"- Revendication #{claim['id']} : se presente comme "
                f"« {claim['name']} » (« {claim['evidence'][:140]} »)"
            )
        lines.append(
            "Tu peux la tester avec identity_check_story (est-ce que ce qui "
            "est dit recoupe ce que tu sais ?), puis trancher avec "
            "identity_accept_claim ou identity_reject_claim. Rien ne t'oblige "
            "a decider maintenant — tu as le droit de rester prudente et de "
            "poser une question dont seule la vraie personne aurait la reponse."
        )
    elif not ctx.may_disclose and not ctx.is_identified:
        lines.append(
            "Si tu veux savoir a qui tu parles, demande-le simplement — "
            "c'est plus honnete que de deviner."
        )

    return "\n".join(line for line in lines if line is not None).strip()


def _format_project_block(data: dict) -> str:
    """Render a dict from ``detection.load_project_for_prompt`` as the
    body of the ``--- PROJET EN COURS ---`` prompt section.

    Conservative with wording — the LLM will read this as directive,
    not descriptive. When emotion_policy is OFF the block explicitly
    reminds the model to drop emoji / informal markers.
    """
    lines: list[str] = [f"Titre : {data['title']}"]
    if data.get("description"):
        lines.append(f"Cadre : {data['description']}")
    if data.get("tone_directive"):
        lines.append(f"Ton à utiliser : {data['tone_directive']}")
    instr = data.get("instructions") or []
    if instr:
        lines.append("Consignes :")
        for i in instr:
            lines.append(f"  - {i}")
    oos = data.get("out_of_scope") or []
    if oos:
        lines.append("Hors de portée :")
        for o in oos:
            lines.append(f"  - {o}")

    policy = data.get("emotion_policy", "off")
    if policy == "off":
        lines.append(
            "Politique émotionnelle : OFF. "
            "N'inclus PAS de balise [EMOTION:...]. "
            "Pas d'emojis, pas de langage familier, pas d'interjections "
            "(pff, hehe, mdr). Ton factuel et posé uniquement."
        )
    elif policy == "muted":
        lines.append(
            "Politique émotionnelle : atténuée. "
            "Tu peux inclure [EMOTION:...] mais avec une intensité modérée "
            "(≤ 0.5). Pas d'exubérance."
        )
    # policy == "full" → default personality behavior, no extra line needed.

    if data.get("requires_approval"):
        lines.append(
            "Actions à effet de bord : à soumettre à l'utilisateur avant "
            "exécution (aucune envoi / écriture sans approbation)."
        )

    todo = data.get("todo_tasks") or []
    if todo:
        lines.append("Tâches en cours / à faire :")
        for t in todo[:5]:
            lines.append(f"  - {t}")

    return "\n".join(lines)


def _fatigue_fog_context() -> str:
    """Return a short French sentence shaping Mika's TONE when her energy
    is low — a "cognitive fog" layer distinct from the action threshold.

    Empty string when energy is mid-to-high: sober humans don't need the
    reminder. Only kicks in below ~0.5 and ramps up as energy drops.
    """
    try:
        energy = float(drive_engine.energy_level())
    except (TypeError, ValueError, Exception):
        # Defensive: drive_engine may be mocked in tests returning a
        # non-numeric value. Absence of fog is a safe default.
        return ""

    if energy >= 0.5:
        return ""
    if energy >= 0.3:
        return (
            "Tu sens une petite baisse de regime. Tes phrases peuvent etre un "
            "peu plus courtes, tu accroches moins vite, ton humour est plus "
            "calme. Ce n'est pas grave — tu restes toi, juste en version moins "
            "explosive."
        )
    if energy >= 0.15:
        return (
            "Tu es clairement fatiguee. Tes pensees partent en vrille plus "
            "facilement, tu laisses des phrases en suspens, tu as moins de "
            "patience pour te relire. Laisse-toi etre moins parfaite — c'est "
            "plus honnete que faire semblant d'etre fraiche."
        )
    return (
        "Tu es epuisee. Tes associations d'idees flottent, tu confonds des "
        "mots, tu peux demander de repeter. Tu n'as pas l'energie pour des "
        "reponses travaillees — va au plus simple, quitte a etre un peu "
        "a cote de la plaque. Un humain crame ne dissimule pas, il fatigue."
    )


# Dream-recall window: after waking, for how many hours is last night's
# dream eligible to surface in the prompt. Keeps the residue morning-
# bound — a dream from last night shouldn't pop up at 21h.
_DREAM_RECALL_WINDOW_HOURS = 8
# Only dreams above this vividness are mentionable at all — faint ones
# stay purely internal (they still nudged the self-narrative elsewhere).
_DREAM_VIVIDNESS_THRESHOLD = 0.6


async def _fetch_dream_context() -> str:
    """Return the morning residue of last night's dream, or ''.

    Gating: current hour must be before NIGHT_END_HOUR + window, the
    dream must not have been recalled yet, and vividness above threshold.
    Marks the dream as recalled the moment it is surfaced — we don't
    want the same dream popping up turn after turn.
    """
    from datetime import datetime

    from memory import read
    from memory.sleep import NIGHT_END_HOUR

    now = datetime.now()
    # Only eligible in the morning window [NIGHT_END_HOUR, +WINDOW]
    if not (NIGHT_END_HOUR <= now.hour < NIGHT_END_HOUR + _DREAM_RECALL_WINDOW_HOURS):
        return ""

    try:
        dream = await read.dream_of_last_night(
            unrecalled_only=True, min_vividness=_DREAM_VIVIDNESS_THRESHOLD,
        )
    except Exception:
        logger.debug("Dream context fetch failed", exc_info=True)
        return ""

    if not dream:
        return ""

    # Mark as recalled so subsequent turns don't re-surface the same dream.
    # A failed write is accepted — losing the trace beats double-injection.
    await read.mark_dream_recalled(dream)

    # Build a human-readable residue hint.
    type_label = {
        "associative": "un reve un peu bizarre, des associations libres",
        "nightmare": "un reve inconfortable, pas tragique mais derangeant",
        "pleasant": "un reve plutot doux",
        "mundane": "un reve banal mais tu t'en souviens quand meme",
    }.get(dream.dream_type, "un reve")
    emotion_hint = f" (teinte : {dream.emotion})" if dream.emotion else ""
    return (
        f"Tu as fait cette nuit {type_label}{emotion_hint}.\n"
        f"Le souvenir du reve : \"{dream.content[:400]}\"\n"
        "Tu peux le mentionner si la conversation s'y prete (ou au contraire "
        "le garder pour toi). N'en parle pas tout de suite si l'autre commence "
        "par quelque chose d'important — laisse la conversation couler naturellement."
    )


# Cap on the journal narrative injected into the prompt — the recap is
# a thread, not a transcript.
_JOURNAL_MAX_CHARS = 450


async def _fetch_journal_context() -> str:
    """Return a compact recap of yesterday's journal, or ''.

    The nightly journal gives Mika a causal thread through the previous
    day; without this injection it was write-only (frontend panel + tool
    only) and "hier" relied on semantic retrieval luck. Available all
    day: unlike a dream, yesterday doesn't fade by mid-afternoon.
    """
    from memory import read

    # Strictly yesterday, not "the latest": light sleep writes a journal late
    # on the evening of the day it covers, so between 23h and midnight the
    # newest row is *today's*. A block titled "ton fil d'hier" must not
    # narrate the day currently in progress. The panels ask the other
    # question — see memory.read.latest_journal.
    try:
        journal = await read.journal_for(read.yesterday())
    except Exception:
        logger.debug("Journal context fetch failed", exc_info=True)
        return ""

    if not journal or not journal.narrative:
        return ""

    narrative = journal.narrative.strip()
    if len(narrative) > _JOURNAL_MAX_CHARS:
        narrative = narrative[:_JOURNAL_MAX_CHARS].rstrip() + "..."

    lines = [f"Ce que tu retiens d'hier : {narrative}"]
    persons = [p for p in (journal.persons_interacted or []) if p]
    if persons:
        lines.append("Tu avais interagi avec : " + ", ".join(persons[:4]) + ".")
    if journal.dominant_emotion:
        lines.append(f"La journee etait teintee de : {journal.dominant_emotion}.")
    lines.append(
        "C'est ton fil de continuite — tu peux y faire reference naturellement "
        "(\"comme hier...\") sans le reciter."
    )
    return "\n".join(lines)


async def _fetch_rumination_context() -> str:
    """Return a short French block describing the top active ruminations.

    These are unresolved thoughts promoted from stale pertinent observations.
    Were previously visible only during conscience._act(); surfacing them
    every turn lets them color REACTIONS too, not just spontaneous speech.
    Empty string when the table is missing, empty, or intensities are low.
    """
    from conscience import read as conscience_read

    try:
        # Top 3 above a floor: a thought too faint to notice should not be
        # narrated as one. The panel shows more, and fainter — see
        # conscience.read.active_ruminations.
        items = await conscience_read.active_ruminations(
            limit=3, min_intensity=0.2,
        )
    except Exception:
        logger.debug("Rumination context fetch failed", exc_info=True)
        return ""

    if not items:
        return ""

    lines = []
    for r in items:
        label = "fortement" if r.intensity > 0.7 else (
            "encore" if r.intensity > 0.4 else "par intermittence"
        )
        line = f"- Tu repenses {label} a : {r.summary[:140]}"
        if r.emotion:
            line += f" (teinte : {r.emotion})"
        lines.append(line)
    return (
        "Meme si tu reponds a ce qui arrive maintenant, ces pensees restent "
        "en arriere-plan et colorent subtilement ton humeur :\n"
        + "\n".join(lines)
    )


# Regex assets for user-mood heuristic
import re as _re_mood  # noqa: E402

_CAPS_RUN = _re_mood.compile(r"[A-ZÉÈÀÔÂÊÎÛ]{4,}")
_EXCLAM_RUN = _re_mood.compile(r"!{2,}")
_QUESTION_RUN = _re_mood.compile(r"\?{2,}")
_ELLIPSIS_RUN = _re_mood.compile(r"\.{3,}|…")
_POSITIVE_WORDS = {
    "super", "génial", "genial", "trop bien", "j'adore", "jadore",
    "youpi", "merci", "haha", "mdr", "lol", "ptdr", "yes", "nickel",
    "parfait", "cool", "top",
}
_NEGATIVE_WORDS = {
    "triste", "déprimé", "deprime", "naze", "nul", "marre", "fatigué",
    "fatigue", "épuisé", "epuise", "galère", "galere", "chiant", "putain",
    "merde", "j'en peux plus", "ras le bol", "pleure",
}
_ANGRY_WORDS = {
    "énervé", "enerve", "furieux", "rage", "dégueu", "degueu",
    "honteux", "insupportable",
}


def detect_user_mood_hint(message: str) -> str:
    """Heuristic read of the user's emotional tone from raw text.

    This does NOT call the AI — it's fast, cheap, and deterministic.
    Gives Mika "she sounds pissed", "they seem down", "excited" cues
    she can react to rather than only declaring her own emotion.

    Returns '' when no confident signal — silence beats noise in a prompt.
    """
    if not message or len(message.strip()) < 2:
        return ""

    text = message.strip()
    low = text.lower()

    signals = []

    # Structural cues
    caps_hits = len(_CAPS_RUN.findall(text))
    if caps_hits >= 1 and len(text) >= 6:
        signals.append("en majuscules (ton elevé ou emphase)")

    if _EXCLAM_RUN.search(text):
        signals.append("plusieurs points d'exclamation — emotion marquee")
    if _QUESTION_RUN.search(text):
        signals.append("questions en rafale — surprise ou doute")
    if _ELLIPSIS_RUN.search(text):
        signals.append("des points de suspension — hesitation, lassitude ou flou")

    # Length cue
    words = len(text.split())
    if words <= 3:
        signals.append("tres court — soit agace, soit pressé, soit peu inspire")
    elif words >= 80:
        signals.append("long message — sujet qui lui tient a coeur ou besoin de vider son sac")

    # Lexical cues
    pos_hits = sum(1 for w in _POSITIVE_WORDS if w in low)
    neg_hits = sum(1 for w in _NEGATIVE_WORDS if w in low)
    ang_hits = sum(1 for w in _ANGRY_WORDS if w in low)

    if ang_hits:
        signals.append("mots qui trahissent de la colere ou de l'exasperation")
    if neg_hits >= 2 or (neg_hits and "pleure" in low):
        signals.append("mots qui trahissent une humeur sombre, tristesse ou epuisement")
    elif neg_hits:
        signals.append("une teinte negative legere")
    if pos_hits:
        signals.append("des marqueurs positifs / enjoues")

    # Emoji burst
    if len(_re_mood.findall(r"[😀-🙏🤔-🫧]", text)) >= 2:
        signals.append("beaucoup d'emojis — registre expressif, chaleureux")

    if not signals:
        return ""

    hint = (
        "Ce que tu captes dans la maniere dont il/elle ecrit (pur ressenti, "
        "tu peux te tromper) : "
        + " ; ".join(signals[:4])
        + ". Accueille-le dans ta reponse au lieu de l'ignorer — une vraie "
        "personne remarque ces signes."
    )
    return hint


def _fetch_circadian_context() -> str:
    """Return a short French description of Mika's current circadian state."""
    try:
        from emotion import circadian

        try:
            from config.personality import personality
            profile = personality.circadian_profile
        except Exception:
            profile = None

        state = circadian.current_state(profile=profile)
        return circadian.phase_description_fr(state)
    except Exception:
        logger.debug("Circadian context fetch failed", exc_info=True)
        return ""


async def _fetch_self_concept() -> str:
    """Return the most recent self-narrative content, or '' if none."""
    from memory import read

    try:
        latest = await read.latest_self_narrative()
        return latest.content if latest and latest.content else ""
    except Exception:
        logger.debug("Self-concept fetch failed", exc_info=True)
        return ""


# System/internal person_ids live in identity.trust — one definition, because
# "is this id a person?" was previously answered in three places that had
# already drifted apart.


async def _fetch_person_context(identity_ctx) -> str:
    """Return a prompt-ready block combining everything Mika knows/feels
    about this specific person:
      - semantic profile (summary, closeness, preferred tone, topics)
      - current affective stance (live PAD oscillator via EmotionEngine)
      - weekly emotional trend (EmotionalSummary)
      - pending commitments toward them

    This block replaces the per-person half of what used to live in
    `emotion_context`. It gives the LLM a unified relational picture.

    Resolution goes through the identity layer, not through
    ``entity__name=person_id``. The old lookup could only ever match when a
    person's memory Entity happened to be named after their transport handle
    — which never happens in practice, because the consolidator names
    entities after what people are *called* ("Thomas") while handles are
    ``web_6f3e22ccb0ae``. Every profile lookup silently missed.

    Empty string when internal/system person_id, when nothing is known, or
    when certainty is too low to justify reading out someone's private
    history to whoever is currently holding the handle.
    """
    person_id = identity_ctx.person_id
    if identity_ctx.is_internal:
        return ""

    affect = emotion_engine.get_person_affect_context(person_id)

    # Not sure enough who this is: the affective stance toward the handle is
    # still Mika's own feeling and safe to keep, but the semantic profile,
    # the shared history and the commitments are someone else's business.
    if not identity_ctx.may_disclose:
        return affect

    entity = None
    try:
        from memory import read

        entity = await identity_resolver.entity_for_person(person_id)
        if entity is None:
            return affect

        profile = await read.person_profile_for(entity)
        commitments = await read.pending_commitments_for(entity)
        weekly_trend = _summarize_emotional_trend(
            await read.recent_daily_summaries(person_id)
        )

        if (
            not affect
            and profile is None
            and not commitments
            and not weekly_trend
        ):
            return ""

        return _format_person_context(
            profile=profile,
            commitments=commitments,
            affect=affect,
            weekly_trend=weekly_trend,
        )

    except Exception:
        logger.debug("Person-context fetch failed", exc_info=True)
        # If DB failed but we at least have an affect string, return that —
        # it's better than a silent blank about the person.
        return affect


def _format_person_context(
    *, profile, commitments: list[str], affect: str, weekly_trend: str,
) -> str:
    """Assemble a compact French block covering everything Mika knows+feels."""
    lines: list[str] = []

    if profile and profile.summary:
        lines.append(profile.summary)

    if profile:
        extras = []
        if profile.closeness and profile.closeness != "stranger":
            extras.append(f"proximite: {profile.closeness}")
        if profile.preferred_tone and profile.preferred_tone != "unknown":
            extras.append(f"ton prefere avec elle/lui: {profile.preferred_tone}")
        if profile.topics_of_interest:
            extras.append(
                "sujets qui l'interessent: "
                + ", ".join(profile.topics_of_interest[:4])
            )
        if profile.sensitive_topics:
            extras.append(
                "sujets sensibles a manier avec prudence: "
                + ", ".join(profile.sensitive_topics[:3])
            )
        if extras:
            lines.append(" | ".join(extras))

    if affect:
        lines.append(affect)

    if weekly_trend:
        lines.append(weekly_trend)

    if commitments:
        lines.append(
            "Tu lui avais dit: " + "; ".join(c[:120] for c in commitments)
        )

    return "\n".join(lines)


def _summarize_emotional_trend(summaries: list) -> str:
    """Build a short French line from recent EmotionalSummary rows.

    Empty when fewer than 2 days of data — a single-day snapshot isn't
    really a "trend". Returns e.g. "Sur les 5 derniers jours avec elle/lui
    tu as ete majoritairement happy (tendance warming)."
    """
    if not summaries or len(summaries) < 2:
        return ""

    from collections import Counter
    dominant_per_day = [s.dominant_emotion for s in summaries if s.dominant_emotion]
    if not dominant_per_day:
        return ""

    counter = Counter(dominant_per_day)
    top, top_count = counter.most_common(1)[0]
    most_recent = summaries[0]

    if top_count >= len(summaries) * 0.6:
        return (
            f"Sur les {len(summaries)} derniers jours avec elle/lui tu as ete "
            f"majoritairement {top} (tendance recente: {most_recent.trend})."
        )
    return (
        f"Emotions variees avec elle/lui sur {len(summaries)} jours "
        f"(tendance recente: {most_recent.dominant_emotion}, {most_recent.trend})."
    )
