"""Context assembly — gather all contextual information for a conversation turn.

``gather_context`` is the orchestration and reads like the « Data Flow » of
CLAUDE.md : one named step per question, in the order that matters. The
steps that read a live singleton (memory buffer, mood, drives, modules,
tools) live here ; the prompt-block formatters live in
``pipeline.context_blocks`` and the history labelling in
``pipeline.context_history``.
"""

import asyncio
import logging
import time as _time
from dataclasses import dataclass, field

from configs.runtime import cfg_int
from drives.engine import drive_engine
from emotion.engine import emotion_engine
from identity import divulgation as div
from identity.resolver import identity_resolver
from identity.trust import is_internal_person
from memory.manager import memory_manager
from modules.manager import module_manager
from pipeline.context_blocks import (
    _MODULE_CONTEXT_MAX_CHARS,
    _clip,
    _fatigue_fog_context,
    _fetch_circadian_context,
    _fetch_dream_context,
    _fetch_journal_context,
    _fetch_person_context,
    _fetch_rumination_context,
    _fetch_self_concept,
    _fetch_travaux_context,
    _format_identity_block,
    _format_project_block,
    detect_user_mood_hint,
    divulgation_du_tour,
)
from pipeline.context_history import _label_history_speakers, _stamp_history_gaps
from pipeline.perception import Intent
from utils.degradation import degradations

logger = logging.getLogger(__name__)


@dataclass
class ConversationContext:
    """All context assembled for a single conversation turn.

    Every field has a default, so ``ConversationContext()`` is a valid empty
    context. That is not laxity: an absent layer and an empty layer mean the
    same thing to ``build_system_prompt`` (skip the block), and requiring six
    of them positionally only forced every caller and test to spell out
    ``memory_context="", tools=[], ...`` to say nothing.
    """
    memory_context: str = ""
    emotion_context: str = ""
    module_context: str = ""
    history: list[dict] = field(default_factory=list)
    # Generic tool list (provider-agnostic ``ModuleTool``); the provider
    # translates to its native tool protocol (MCP, function-calling, …).
    tools: list = field(default_factory=list)
    tool_names: list[str] = field(default_factory=list)
    # Self-concept: evolving autobiographical paragraph, regenerated by
    # the consolidator. Empty string if no narrative has been produced yet.
    self_concept: str = ""
    # Theory of mind: what Mika knows/assumes about the current person,
    # plus her pending commitments toward them. Empty if no profile
    # exists yet for this person_id.
    person_context: str = ""
    # Circadian state — current phase + energy level description, nudges
    # Mika's tone to match the time of day.
    circadian_context: str = ""
    # Fatigue/cognitive fog — when energy is low, Mika's thoughts blur.
    # Shapes TONE (not just the act/wait threshold).
    fatigue_fog: str = ""
    # Active ruminations — unresolved pertinent thoughts still on her mind.
    # Was previously surfaced only inside _act(); now visible every turn.
    rumination_context: str = ""
    # Les chantiers qu'elle a ouverts (conscience.Travail) — en cours et
    # aboutis du jour. Sans ce bloc, « tu fais quoi en ce moment ? » était la
    # seule question sur sa propre vie à laquelle elle ne savait pas
    # répondre : le tableau de bord voyait ses chantiers, elle non.
    travaux_context: str = ""
    # Best-effort heuristic read of the user's emotional tone (caps, emojis,
    # length, keywords). Gives Mika something to react to, not just declare.
    user_mood_hint: str = ""
    # The morning-after residue of a vivid dream from last night, if any.
    # Only injected until early afternoon and only for non-internal persons,
    # so Mika can spontaneously mention it in the first few conversations.
    dream_context: str = ""
    # Yesterday's journal — the narrative thread of the previous day, so
    # "hier" is something Mika actually remembers as a day, not just as
    # disconnected souvenirs surfaced by semantic luck.
    journal_context: str = ""
    # Project layer — set when an active Project matches the current turn
    # (user talked about it, owner mentioned, keyword hit). The string is
    # injected as `--- PROJET EN COURS ---`; the boolean forces the
    # personality prompt into "professional mode" (no emotion tag, no
    # variability block) when the matched project's emotion_policy=OFF.
    project_context: str = ""
    project_suppresses_emotion: bool = False
    # ID of the matched project — not injected in the prompt, but passed
    # through so the processor can tag outgoing side effects / skip the
    # emotion impulse when the project is "off".
    project_id: int | None = None
    # Who Mika thinks she is talking to and how sure she is — injected as
    # `--- QUI TU AS EN FACE ---`. Also gates `person_context`: below the
    # disclosure threshold, private per-person memory is withheld entirely.
    identity_context: str = ""
    # Le niveau de divulgation du tour (``identity.divulgation``) : ce que la
    # mémoire a pu servir sur AUTRUI, en deux facettes. Calculé une fois au
    # bord, passé au rappel et au journal ; porté ici pour que le tour dise
    # sous quel niveau il a été composé. ``FERME`` par défaut : fail-closed.
    niveau_divulgation: div.Divulgation = div.FERME

    # Pensée pré-verbale produite par la passe de préparation — injectée en
    # dernier (`--- CE QUI TE VIENT A L'ESPRIT ---`), là où la récence pèse
    # le plus. Vide quand la passe n'a pas tourné ou n'avait rien à dire.
    note_de_focus: str = ""

    # Résumé roulant du fil (compaction) — matériau de la zone messages,
    # PAS une couche du prompt système : rendu comme premier tour user par
    # ChatPrompt, dans la zone cacheable.
    conversation_summary: str = ""

    # Le `Dream` injecté dans `dream_context`, en attente d'être consommé.
    # Volontairement hors de `_LAYERS` : ce n'est pas un bloc de prompt mais
    # l'instance que le processor marque comme rappelée *si* le tour aboutit.
    pending_dream_recall: object | None = None


async def gather_context(
    message: str,
    person_id: str,
    include_tools: bool = True,
    channel: str = "",
    authenticated: bool = False,
    is_public: bool = False,
    include_memory: bool = True,
    intent: Intent = Intent.REQUEST_RESPONSE,
) -> ConversationContext:
    """Assemble all context needed for an AI conversation turn.

    Args:
        message: The user/trigger message (used for memory retrieval).
        person_id: Who is talking (for emotion + memory boosting).
        include_tools: Whether to include MCP tools from modules.
        channel: Transport the turn arrived on ("web", "telegram", …), used
            to decide how much the channel itself proves about the sender.
        authenticated: The transport verified this session's credentials.
        is_public: The turn happened in a shared room, not a 1:1 exchange.
        include_memory: Whether to run the semantic retrieval. False for a
            caller that already holds the souvenirs it wants injected — the
            conscience recalls on the observations themselves, then overrode
            this field, so the embedding + ChromaDB query paid here was
            thrown away on every spontaneous act.
        intent: What kind of stimulus this is. Only a ``REQUEST_RESPONSE``
            carries text somebody actually wrote — see ``user_mood_hint``.

    L'ordre des étapes est porteur : l'identité d'abord (le rappel en
    dépend), le rappel mémoire *lancé* ensuite et *attendu* en dernier, pour
    que la deadline du plan de préparation soit masquée par la dizaine de
    lectures qu'il fallait faire de toute façon.
    """
    # Qui est en face, et à quel point elle en est sûre — résolu avant tout
    # le reste, puis le NIVEAU de divulgation du tour (ce que la mémoire peut
    # servir sur autrui) : le rappel ne doit pas servir les confidences d'un
    # tiers alors que le bloc « CE QUE TU SAIS DE CETTE PERSONNE » vient
    # d'être fermé pour la même raison.
    identity_ctx = await identity_resolver.resolve_context(
        person_id, channel=channel,
        authenticated=authenticated, is_public=is_public,
    )
    divulgation = await divulgation_du_tour(identity_ctx)
    interne = is_internal_person(person_id)

    rappel = _lancer_le_rappel(message, person_id, include_memory, divulgation)

    # Tout ce qui ne dépend pas du rappel tourne PENDANT le plan.
    self_concept = await _fetch_self_concept()
    person_context = await _fetch_person_context(identity_ctx)
    circadian_context = _fetch_circadian_context()
    emotion_context = _humeur_et_pulsions()
    module_context = _contexte_modules(person_id)
    history, conversation_summary = await _fil_de_conversation(person_id)
    fatigue_fog = await _etat_cognitif()
    rumination_context = await _fetch_rumination_context()
    travaux_context = await _fetch_travaux_context()
    user_mood_hint = _ton_de_la_personne(message, person_id, intent)
    dream_context, pending_dream_recall, journal_context = await _reve_et_journal(
        interne, divulgation.niveau,
    )
    project_context, project_suppresses_emotion, project_id = await _projet_du_tour(
        message, person_id, interne,
    )

    memory_context, note_de_focus = await _achever_le_rappel(
        rappel, message, person_id, divulgation,
    )
    tools, tool_names = _outils_de_la_conversation(include_tools)

    return ConversationContext(
        memory_context=memory_context,
        emotion_context=emotion_context,
        module_context=module_context,
        history=history,
        tools=tools,
        tool_names=tool_names,
        self_concept=self_concept,
        person_context=person_context,
        circadian_context=circadian_context,
        fatigue_fog=fatigue_fog,
        rumination_context=rumination_context,
        travaux_context=travaux_context,
        user_mood_hint=user_mood_hint,
        dream_context=dream_context,
        journal_context=journal_context,
        project_context=project_context,
        project_suppresses_emotion=project_suppresses_emotion,
        project_id=project_id,
        identity_context=_format_identity_block(identity_ctx),
        niveau_divulgation=divulgation,
        note_de_focus=note_de_focus,
        conversation_summary=conversation_summary,
        pending_dream_recall=pending_dream_recall,
    )


# ── Rappel mémoire : spéculatif (plancher) + plan de préparation ────────────
#
# Le spéculatif est la recherche historique sur le message ; la passe de
# préparation (petit LLM, pipeline/preparation.py) tourne EN PARALLÈLE et
# peut la remplacer par un rappel dirigé (multi-requêtes + échanges bruts).
# Deadline dure, fail-open : la réponse n'attend jamais la réflexion, et tout
# échec redonne exactement le comportement d'avant.


@dataclass
class _RappelEnCours:
    """Les deux tâches lancées en tête de tour, attendues en queue."""
    spec_task: asyncio.Task
    prep_task: asyncio.Task | None
    prep_deadline: float


def _lancer_le_rappel(
    message: str, person_id: str, include_memory: bool,
    divulgation: div.Divulgation,
) -> _RappelEnCours | None:
    """Lance le plan et la recherche spéculative ; ``None`` sans rappel."""
    if not include_memory:
        return None
    prep_task, prep_deadline = _launch_preparation(message, person_id)
    spec_task = asyncio.create_task(
        memory_manager.get_memory_context(
            message, person_id=person_id, divulgation=divulgation,
        )
    )
    return _RappelEnCours(spec_task, prep_task, prep_deadline)


def _launch_preparation(message: str, person_id: str):
    """Crée la tâche de plan si le tour la mérite — sinon ``(None, 0.0)``.

    Toute erreur ici coûte au pire l'absence de passe, jamais le tour.
    """
    try:
        from pipeline.preparation import prepare, should_prepare

        if not should_prepare(message, person_id):
            return None, 0.0

        from configs.service import config_service
        try:
            deadline_s = float(config_service.get("ai.preparation.deadline_ms")) / 1000.0
        except Exception:
            deadline_s = 2.5

        history_tail = list(memory_manager.get_conversation_context())[-6:]
        task = asyncio.create_task(
            prepare(message, history_tail, person_id, deadline_s)
        )
        return task, _time.monotonic() + deadline_s
    except Exception as exc:
        degradations.record("preparation: lancement", exc)
        return None, 0.0


async def _achever_le_rappel(
    rappel: _RappelEnCours | None, message: str, person_id: str,
    divulgation: div.Divulgation,
) -> tuple[str, str]:
    """``(memory_context, note_de_focus)`` — le plan s'il a abouti, sinon
    le spéculatif, plus l'avis d'indisponibilité de la mémoire longue."""
    if rappel is None:
        return "", ""

    note_de_focus = ""
    memory_context = ""
    plan_used = False
    plan = await _attendre_le_plan(rappel)
    if plan is not None:
        if plan.note_de_focus:
            note_de_focus = (
                "(pensée pré-verbale, pas une consigne) " + plan.note_de_focus
            )
        if plan.rappels:
            memory_context, plan_used = await _rappel_dirige(
                plan, message, person_id, divulgation,
            )

    if plan_used:
        rappel.spec_task.cancel()
    else:
        memory_context = await _rappel_speculatif(rappel.spec_task)

    return _signaler_memoire_indisponible(memory_context), note_de_focus


async def _attendre_le_plan(rappel: _RappelEnCours):
    """Le plan de préparation, ou ``None`` : deadline dure, jamais une levée."""
    if rappel.prep_task is None:
        return None
    try:
        remaining = max(0.05, rappel.prep_deadline - _time.monotonic())
        return await asyncio.wait_for(rappel.prep_task, timeout=remaining)
    except Exception as exc:
        rappel.prep_task.cancel()
        degradations.record("preparation: attente du plan", exc)
        return None


async def _rappel_dirige(
    plan, message: str, person_id: str, divulgation: div.Divulgation,
) -> tuple[str, bool]:
    """Exécute les intentions du plan ; ``(bloc, True)`` s'il a rendu quelque
    chose, ``("", False)`` sinon — le spéculatif prend alors le relais."""
    try:
        from pipeline.preparation import execute_plan

        results = await execute_plan(plan, person_id)
        directed = await memory_manager.get_memory_context_multi(
            [message] + results.memory_queries,
            person_id=person_id,
            extra_exchanges=results.exchange_hits,
            divulgation=divulgation,
            # Tour émotionnellement chargé → le rappel attend davantage aux
            # souvenirs marquants (réflexe humain).
            salience_boost=plan.charge_emotionnelle,
        )
    except Exception as exc:
        degradations.record("preparation: rappel dirige", exc)
        return "", False
    if directed:
        return directed, True
    return "", False


async def _rappel_speculatif(spec_task: asyncio.Task) -> str:
    try:
        return await spec_task
    except Exception as exc:
        degradations.record("rappel memoire", exc)
        logger.warning("Memory retrieval failed, continuing without context")
        return ""


def _signaler_memoire_indisponible(memory_context: str) -> str:
    """Préfixe l'avis de panne de la mémoire longue quand le manager le dit.

    Un rappel vide est le cas nominal d'une base jeune ; une mémoire longue
    en panne ne l'est pas. Le drapeau vient du manager, jamais déduit d'un
    bloc vide — sinon le prompt annoncerait une panne dès le premier jour.
    Le dire lui permet de répondre « je ne retrouve pas » au lieu de
    confabuler. ``is True`` et non une vérité pythonique : les tests
    substituent le manager par un mock, dont tout attribut est truthy.
    """
    if getattr(memory_manager, "recall_unavailable", False) is not True:
        return memory_context
    notice = (
        "[Ta memoire longue est indisponible en ce moment : tu ne "
        "peux rien y retrouver. Dis-le simplement si ca compte pour "
        "la conversation, plutot que d'inventer un souvenir.]"
    )
    return f"{notice}\n{memory_context}" if memory_context else notice


# ── Les lectures d'état qui ne dépendent pas du rappel ─────────────────────


def _humeur_et_pulsions() -> str:
    """Le bloc émotionnel = l'humeur globale de Mika + ses pulsions.

    La stance affective envers la personne est relationnelle et appartient
    à ``person_context`` : le prompt sépare « comment Mika se sent » de
    « comment elle se sent envers cette personne ». Lecture seule des
    pulsions : les assouvir est la politique de ``drives/apps.py`` sur
    ``_turn.completed`` — appeler ``on_conversation`` ici compterait deux fois.
    """
    emotion_context = emotion_engine.get_global_mood_context()
    drive_context = drive_engine.get_context()
    if drive_context:
        return f"{emotion_context}\n{drive_context}" if emotion_context else drive_context
    return emotion_context


def _contexte_modules(person_id: str) -> str:
    """Le contexte des modules pour cette personne, plafonné ici et non dans
    le collecteur : chaque module se borne, leur somme (Forge inclus) non."""
    return _clip(
        module_manager.collect_context(person_id),
        cfg_int("pipeline.context.module_context_max_chars",
                _MODULE_CONTEXT_MAX_CHARS, mini=1),
    )


async def _fil_de_conversation(person_id: str) -> tuple[list[dict], str]:
    """``(historique, résumé de compaction)``.

    L'historique est daté (trous) et annoté de qui parle quand ce n'est pas
    la personne en face : le tampon est partagé par tout le monde, et
    l'arbitrage confié à Mika suppose qu'elle distingue les tours. Le résumé
    est coercé : les tests substituent le manager par un mock dont
    l'attribut rendrait un objet.
    """
    history = await _stamp_history_gaps(memory_manager.get_conversation_context())
    history = await _label_history_speakers(history, person_id)
    summary = getattr(memory_manager, "get_conversation_summary", lambda: "")()
    return history, (summary if isinstance(summary, str) else "")


async def _etat_cognitif() -> str:
    """Brouillard de fatigue + la ligne d'estime de soi.

    L'estime rejoint l'état cognitif : le doute ou l'assurance sont une
    couleur de pensée, pas une émotion du moment. Lue par l'API du module
    (``conscience/estime.py`` EST sa couche de lecture) — un sentiment dans
    le prompt, jamais un nombre. L'équilibre est silencieux.
    """
    fatigue_fog = _fatigue_fog_context()
    try:
        from conscience import estime as estime_module

        ligne_estime = estime_module.ligne_de_prompt(await estime_module.lire())
        if ligne_estime:
            fatigue_fog = (fatigue_fog + "\n" + ligne_estime).strip()
    except Exception as exc:
        degradations.record("prompt: estime de soi", exc)
    return fatigue_fog


def _ton_de_la_personne(message: str, person_id: str, intent: Intent) -> str:
    """Lecture heuristique du ton — gardée sur l'*intent*, pas seulement sur
    la personne : un déclencheur interne visant une vraie personne porte son
    handle, et la porte personne laissait lire le brief que Mika s'écrit
    comme le ton de l'autre. On ne lit pas le ton d'un texte que personne
    n'a envoyé."""
    if intent is not Intent.REQUEST_RESPONSE or is_internal_person(person_id):
        return ""
    return detect_user_mood_hint(message)


async def _reve_et_journal(
    interne: bool, niveau: div.Niveau,
) -> tuple[str, object | None, str]:
    """``(rêve, Dream en attente, journal d'hier)`` — rien pour un
    déclencheur interne : le résidu du rêve et le fil d'hier ne s'adressent
    qu'à de vrais interlocuteurs."""
    if interne:
        return "", None, ""
    dream_context, pending_dream = await _fetch_dream_context()
    journal_context = await _fetch_journal_context(niveau=niveau)
    return dream_context, pending_dream, journal_context


async def _projet_du_tour(
    message: str, person_id: str, interne: bool,
) -> tuple[str, bool, int | None]:
    """``(bloc projet, mode professionnel, id)`` du projet actif que ce tour
    concerne — jamais pour un déclencheur interne (un prompt de la
    conscience ne doit pas référencer par erreur un projet confié)."""
    if interne:
        return "", False, None
    try:
        from projects.detection import detect_project_for_message, load_project_for_prompt

        match = await detect_project_for_message(message, person_id=person_id)
        if match:
            data = await load_project_for_prompt(match.project_id)
            if data:
                return (
                    _format_project_block(data),
                    data["emotion_policy"] == "off",
                    data["id"],
                )
    except Exception as exc:
        degradations.record("prompt: project detection", exc)
    return "", False, None


# ── Les outils de la conversation ───────────────────────────────────────────


def _outils_de_la_conversation(include_tools: bool) -> tuple[list, list[str]]:
    """Liste générique de ``ModuleTool`` (le provider traduit) + leurs noms.

    ``ai.conversation_tool_modules`` restreint à une allow-list de modules.
    Vide = tous les modules en marche : juste derrière une API hébergée, faux
    derrière un modèle local — une déclaration d'outil est du prompt renvoyé
    à chaque itération de la boucle, et les neuf modules pèsent ~6 500
    jetons, quatre fois le prompt système. Le réglage vit en configuration
    parce que la bonne réponse est une propriété du modèle derrière le rôle.
    """
    if not include_tools:
        return [], []
    allowed = _conversation_tool_modules()
    tools = (
        module_manager.get_tools_for_modules(allowed) if allowed
        else module_manager.collect_tools()
    )
    return tools, [t.name for t in tools]


def _conversation_tool_modules() -> list[str]:
    """Module allow-list for conversation tools — empty means "all of them".

    Read per turn rather than cached: the setting is ``hot_reload``, and the
    point of the knob is to try a narrower set against a live conversation
    without a restart. Never raises — an unreadable config must cost a
    lighter tool set at worst, never the answer itself.
    """
    from configs.service import config_service

    try:
        raw = config_service.get("ai.conversation_tool_modules") or []
    except Exception as exc:
        degradations.record("prompt: conversation tool allow-list", exc)
        return []
    if isinstance(raw, str):
        raw = [part.strip() for part in raw.split(",")]
    return [name for name in (str(n).strip() for n in raw) if name]
