"""Context assembly — gather all contextual information for a conversation turn.

Collects memory, emotion, module context, and conversation history
into a single structure ready for the AI call.
"""

import logging
from dataclasses import dataclass

from drives.engine import drive_engine
from emotion.engine import emotion_engine
from memory.manager import memory_manager

logger = logging.getLogger(__name__)


@dataclass
class ConversationContext:
    """All context assembled for a single conversation turn."""
    memory_context: str
    emotion_context: str
    module_context: str
    history: list[dict]
    mcp_server: object | None  # SdkMcpServer or None
    tool_names: list[str]
    # Self-concept: evolving autobiographical paragraph, regenerated by
    # the consolidator. Empty string if no narrative has been produced yet.
    self_concept: str = ""


async def gather_context(
    message: str,
    person_id: str,
    include_tools: bool = True,
) -> ConversationContext:
    """Assemble all context needed for an AI conversation turn.

    Args:
        message: The user/trigger message (used for memory retrieval).
        person_id: Who is talking (for emotion + memory boosting).
        include_tools: Whether to include MCP tools from modules.
    """
    from modules.manager import module_manager

    # Memory context (graceful degradation)
    try:
        memory_context = await memory_manager.get_memory_context(
            message, person_id=person_id
        )
    except Exception:
        logger.warning("Memory retrieval failed, continuing without context")
        memory_context = ""

    # Self-concept: latest autobiographical narrative from the consolidator.
    # Best-effort — if the table hasn't been populated yet (no narrative
    # generated), we just skip it and the prompt uses personality alone.
    self_concept = await _fetch_self_concept()

    # Emotion context for this person
    emotion_context = emotion_engine.get_emotion_context(person_id)

    # Intrinsic drives — append to the emotional layer so Claude sees
    # Mika's pulls (curiosity/social/expression/rest) alongside mood.
    drive_context = drive_engine.get_context()
    if drive_context:
        emotion_context = (
            f"{emotion_context}\n{drive_context}" if emotion_context else drive_context
        )

    # Also satisfy the social drive when a real person is about to be answered.
    if person_id not in ("conscience_mika", "__global__", "anonymous"):
        drive_engine.on_conversation(from_person=True)

    # Module context for system prompt
    module_context = module_manager.collect_context()

    # Conversation history
    history = memory_manager.get_conversation_context()

    # Tools
    mcp_server = None
    tool_names = []
    if include_tools:
        mcp_server = module_manager.get_mcp_server()
        tool_names = module_manager.get_tool_names()

    return ConversationContext(
        memory_context=memory_context,
        emotion_context=emotion_context,
        module_context=module_context,
        history=history,
        mcp_server=mcp_server,
        tool_names=tool_names,
        self_concept=self_concept,
    )


async def _fetch_self_concept() -> str:
    """Return the most recent self-narrative content, or '' if none."""
    try:
        from asgiref.sync import sync_to_async

        from memory.models import SelfNarrative

        latest = await sync_to_async(
            lambda: SelfNarrative.objects.order_by("-created_at").first()
        )()
        return latest.content if latest and latest.content else ""
    except Exception:
        logger.debug("Self-concept fetch failed", exc_info=True)
        return ""
