# Generated by Django 6.0 on 2026-09-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiquotausage',
            new_name='ai_aiquotau_date_f162e7_idx',
            old_name='ai_aiquotau_date_role_idx',
        ),
        migrations.RenameIndex(
            model_name='aiquotausage',
            new_name='ai_aiquotau_date_75f9c8_idx',
            old_name='ai_aiquotau_date_proj_idx',
        ),
    ]
