# Generated by Django 6.0 on 2026-09-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configchangelog',
            new_name='configs_con_created_682495_idx',
            old_name='configs_con_created_idx',
        ),
        migrations.RenameIndex(
            model_name='configchangelog',
            new_name='configs_con_key_a3f824_idx',
            old_name='configs_con_key_crt_idx',
        ),
        migrations.RenameIndex(
            model_name='configrecorditem',
            new_name='configs_con_parent__c7af2e_idx',
            old_name='configs_con_parent__idx',
        ),
        migrations.RenameIndex(
            model_name='configrecorditem',
            new_name='configs_con_row_id_4d7c82_idx',
            old_name='configs_con_row_id_idx',
        ),
        migrations.RenameIndex(
            model_name='configvalue',
            new_name='configs_con_key_b5de80_idx',
            old_name='configs_con_key_idx',
        ),
    ]
