# Generated by Django 6.0 on 2026-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_consolidationlog_theme_message_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='person_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
