# Generated by Django 6.0 on 2026-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_connaissance_memory_conn_is_vali_53281a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=100)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('period_start', models.DateField()),
                ('dominant_emotion', models.CharField(max_length=30)),
                ('dominant_intensity', models.FloatField(default=0.0)),
                ('emotion_distribution', models.JSONField(default=dict)),
                ('trend', models.CharField(default='stable', max_length=20)),
                ('snapshot_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['person_id', '-period_start'], name='memory_emot_person__8c06e9_idx')],
                'unique_together': {('person_id', 'period_type', 'period_start')},
            },
        ),
    ]
