# Generated by Django 5.2.1 on 2026-04-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0008_message_pk_secondary_sort'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commitment',
            new_name='memory_comm_status_780cba_idx',
            old_name='memory_comm_status_01c2e8_idx',
        ),
        migrations.RenameIndex(
            model_name='commitment',
            new_name='memory_comm_person__39b3a4_idx',
            old_name='memory_comm_person__f1de45_idx',
        ),
        migrations.RenameIndex(
            model_name='personprofile',
            new_name='memory_pers_last_in_d97baf_idx',
            old_name='memory_pers_last_in_e391a7_idx',
        ),
        migrations.RenameIndex(
            model_name='personprofile',
            new_name='memory_pers_generat_4e2130_idx',
            old_name='memory_pers_generat_5a8c14_idx',
        ),
        migrations.RenameIndex(
            model_name='selfnarrative',
            new_name='memory_self_created_9b8be6_idx',
            old_name='memory_self_created_idx',
        ),
    ]
