# Generated by Django 5.2.1 on 2026-04-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0006_rename_conscience__status_8a2f11_idx_conscience__status_187012_idx'),
        ('memory', '0010_message_attachments_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('narrative', models.TextField(help_text="First-person paragraph covering the day's arc.")),
                ('key_moments', models.JSONField(default=list)),
                ('dominant_emotion', models.CharField(blank=True, default='', max_length=30)),
                ('persons_interacted', models.JSONField(default=list)),
                ('unresolved_at_sleep', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='memory_dail_date_d23cd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_of', models.DateField()),
                ('content', models.TextField(help_text='The dream narrative: 2-4 short sentences, first-person.')),
                ('dream_type', models.CharField(choices=[('associative', 'Associative'), ('nightmare', 'Nightmare'), ('pleasant', 'Pleasant'), ('mundane', 'Mundane')], default='associative', max_length=20)),
                ('vividness', models.FloatField(default=0.5)),
                ('emotion', models.CharField(blank=True, default='', help_text='Dominant emotion of the dream.', max_length=30)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_rumination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dreams', to='conscience.rumination')),
                ('source_souvenirs', models.ManyToManyField(blank=True, related_name='dreams', to='memory.souvenir')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-night_of'], name='memory_drea_night_o_b6949d_idx'), models.Index(fields=['recalled_at', '-vividness'], name='memory_drea_recalle_760c89_idx')],
            },
        ),
    ]
