# Generated by Django 6.0 on 2026-07-26 20:44

from django.db import migrations, models
from django.utils import timezone


def _anchor_existing(apps, schema_editor):
    """Stamp existing souvenirs as decayed-now.

    Their stored importance already reflects the old absolute rate**age
    formula; anchoring at occurred_at instead would replay that whole decay
    a second time and prune legitimate memories.
    """
    Souvenir = apps.get_model('memory', 'Souvenir')
    Souvenir.objects.filter(decayed_at__isnull=True).update(
        decayed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0011_dailyjournal_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='decayed_at',
            field=models.DateTimeField(blank=True, help_text='Anchor for time-based decay. Decay multiplies the CURRENT importance by rate^(days since this stamp), so conscience boosts and hand-set importances survive instead of being recomputed from age alone.', null=True),
        ),
        migrations.RunPython(_anchor_existing, migrations.RunPython.noop),
    ]
