# Generated by Django 6.0 on 2026-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0013_message_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='connaissance',
            name='decayed_at',
            field=models.DateTimeField(blank=True, help_text="Anchor for confidence decay, mirroring Souvenir.decayed_at. Decay used to be measured from updated_at, which save(update_fields=['confidence']) never advances (auto_now only fires for fields being written) — so every tick re-subtracted the full elapsed decay and a week-old fact hit the floor in minutes instead of months.", null=True),
        ),
        migrations.AddIndex(
            model_name='connaissance',
            index=models.Index(fields=['decayed_at'], name='memory_conn_decayed_f2a444_idx'),
        ),
        migrations.AddIndex(
            model_name='souvenir',
            index=models.Index(fields=['decayed_at'], name='memory_souv_decayed_a5626e_idx'),
        ),
    ]
