# Generated by Django 6.0 on 2026-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0015_message_awaiting_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodicIndexLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_id', models.IntegerField(default=0)),
                ('chunks_created', models.IntegerField(default=0)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emotionsnapshot',
            index=models.Index(fields=['person_id', '-created_at'], name='memory_emot_person__d5ff66_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionsnapshot',
            index=models.Index(fields=['-created_at'], name='memory_emot_created_7077a8_idx'),
        ),
    ]
