using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Mika.Editor.Animation
{
    /// <summary>
    /// Le poids des cheveux et des vêtements de Mika. Le modèle livre ses ressorts sans gravité (rigidité 1,
    /// gravité 0) : les couettes gardent leur forme au repos mais, dès qu'elle bouge (marcher, s'asseoir), plus
    /// rien ne les retient — elles flottent à l'horizontale comme dans l'eau. On leur rend un poids et un
    /// amortissement par famille de chaîne (le nom que le modèle leur donne), dans le préfabriqué de l'avatar.
    /// </summary>
    public static class SpringTuning
    {
        const string PrefabPath = "Assets/Mika/Art/Avatars/Mika.prefab";

        /// <summary>Par famille : rigidité, gravité, amortissement (0 → 1).</summary>
        static readonly Dictionary<string, (float stiffness, float gravity, float drag)> Families =
            new Dictionary<string, (float, float, float)>
            {
                // Les longues couettes : lourdes, elles suivent la tête avec un peu de retard, sans battre.
                ["HairTail"] = (1.6f, 0.6f, 0.85f),
                // Mèches avant et côtés : courtes, plus raides (elles encadrent le visage).
                ["HairFront"] = (2.2f, 0.12f, 0.8f),
                ["HairSide"] = (1.8f, 0.3f, 0.82f),
                ["HairOthers"] = (2.0f, 0.1f, 0.75f),
                ["HairRibbon"] = (1.6f, 0.15f, 0.72f),
                // La jupe et les pans du manteau : tissu, un peu de poids, bien amorti.
                ["Generated by VRMSkirtTool 1.1.2"] = (1.4f, 0.15f, 0.65f),
                ["Cloth"] = (1.3f, 0.2f, 0.65f),
                ["Cable"] = (1.2f, 0.25f, 0.7f),
            };

        [MenuItem("Mika/Animation/Régler le poids des cheveux et des vêtements", priority = 22)]
        public static void Apply() => Apply(1f);

        /// <param name="scale">Un facteur sur la gravité (essais).</param>
        public static int Apply(float scale)
        {
            var root = PrefabUtility.LoadPrefabContents(PrefabPath);
            var changed = 0;
            try
            {
                Component instance = null;
                foreach (var c in root.GetComponentsInChildren<Component>(true))
                    if (c != null && c.GetType().Name == "Vrm10Instance")
                        instance = c;
                if (instance == null)
                {
                    Debug.LogWarning("[Mika] ressorts : pas de Vrm10Instance dans l'avatar.");
                    return 0;
                }
                var springs = new SerializedObject(instance).FindProperty("SpringBone.Springs");
                for (var i = 0; i < springs.arraySize; i++)
                {
                    var spring = springs.GetArrayElementAtIndex(i);
                    var name = spring.FindPropertyRelative("Name").stringValue;
                    if (!Families.TryGetValue(name, out var p)) continue;
                    var joints = spring.FindPropertyRelative("Joints");
                    for (var j = 0; j < joints.arraySize; j++)
                    {
                        var joint = joints.GetArrayElementAtIndex(j).objectReferenceValue;
                        if (joint == null) continue;
                        var js = new SerializedObject(joint);
                        js.FindProperty("m_stiffnessForce").floatValue = p.stiffness;
                        js.FindProperty("m_gravityPower").floatValue = p.gravity * scale;
                        js.FindProperty("m_dragForce").floatValue = p.drag;
                        js.ApplyModifiedPropertiesWithoutUndo();
                        changed++;
                    }
                }
                PrefabUtility.SaveAsPrefabAsset(root, PrefabPath);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
            Debug.Log($"[Mika] ressorts réglés : {changed} articulations.");
            return changed;
        }
    }
}
