# Generated by Django 6.0 on 2026-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, unique=True)),
                ('tension', models.FloatField(default=0.0)),
                ('last_satisfied', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'instantané de pulsion',
                'verbose_name_plural': 'instantanés de pulsions',
            },
        ),
    ]
