# Generated by Django 6.0 on 2026-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0008_conscience_log_trousse'),
    ]

    operations = [
        migrations.AddField(
            model_name='consciencelog',
            name='conduite',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('origine', models.CharField(choices=[('observation', 'Observation'), ('pensee', 'Pensee'), ('pulsion', 'Pulsion')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('envie', models.FloatField(default=0.5)),
                ('ancre_envie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En Cours'), ('aboutie', 'Aboutie'), ('bloquee', 'Bloquee'), ('abandonnee', 'Abandonnee')], default='en_cours', max_length=15)),
                ('raison_blocage', models.TextField(blank=True, default='')),
                ('resultat', models.TextField(blank=True, default='')),
                ('pas_effectues', models.IntegerField(default=0)),
                ('pas_max', models.IntegerField(default=5)),
                ('dernier_pas_le', models.DateTimeField(blank=True, null=True)),
                ('en_attente_de_reponse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-envie', '-created_at'],
                'indexes': [models.Index(fields=['statut', '-envie'], name='conscience__statut_61be67_idx'), models.Index(fields=['statut', 'origine', 'reference'], name='conscience__statut_3d467f_idx')],
            },
        ),
    ]
