# Generated by Django 6.0 on 2026-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0009_travail_et_conduite'),
    ]

    operations = [
        migrations.AddField(
            model_name='consciencelog',
            name='acts_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='consecutive_ignored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='cooldown_restant_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='energie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='outils',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='person_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='sleep_phase',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='consciencelog',
            name='texte',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='raison_echec',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='resultat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='tentatives',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
