# Generated by Django 6.0 on 2026-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conscience', '0013_observation_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='attend_qui',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
