# Generated by Django 6.0.2 on 2026-02-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_processed', models.IntegerField()),
                ('souvenirs_created', models.IntegerField(default=0)),
                ('connaissances_created', models.IntegerField(default=0)),
                ('last_message_id', models.IntegerField(default=0)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='emotion',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='emotion_intensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='EmotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(default='anonymous', max_length=100)),
                ('primary_emotion', models.CharField(max_length=30)),
                ('primary_intensity', models.FloatField()),
                ('global_emotion', models.CharField(default='neutral', max_length=30)),
                ('global_intensity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_snapshots', to='memory.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('object', 'Object'), ('place', 'Place'), ('concept', 'Concept')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['name'],
                'unique_together': {('name', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('emotion', models.CharField(default='neutral', help_text='How the VTuber felt about this event', max_length=30)),
                ('importance', models.FloatField(default=1.0)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souvenirs', to='memory.conversation')),
                ('entities', models.ManyToManyField(blank=True, related_name='souvenirs', to='memory.entity')),
                ('themes', models.ManyToManyField(blank=True, related_name='souvenirs', to='memory.theme')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Connaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entities', models.ManyToManyField(blank=True, related_name='connaissances', to='memory.entity')),
                ('source_souvenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_connaissances', to='memory.souvenir')),
                ('themes', models.ManyToManyField(blank=True, related_name='connaissances', to='memory.theme')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
