# Generated by Django 6.0 on 2026-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_message_person_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connaissance',
            index=models.Index(fields=['is_valid', '-confidence'], name='memory_conn_is_vali_53281a_idx'),
        ),
        migrations.AddIndex(
            model_name='connaissance',
            index=models.Index(fields=['-updated_at'], name='memory_conn_updated_21d03d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='memory_mess_created_6446c9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='memory_mess_convers_9cedd0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['person_id', 'created_at'], name='memory_mess_person__317cac_idx'),
        ),
        migrations.AddIndex(
            model_name='souvenir',
            index=models.Index(fields=['-importance'], name='memory_souv_importa_ac0cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='souvenir',
            index=models.Index(fields=['-occurred_at'], name='memory_souv_occurre_523d37_idx'),
        ),
    ]
