# Generated by Django 6.0 on 2026-07-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0012_souvenir_decayed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
