# Generated by Django 6.0 on 2026-07-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0014_connaissance_decayed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='awaiting_reply',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
