# Generated by Django 6.1.1 on 2026-09-16 21:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0018_message_transport_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodicindexlog',
            name='last_message_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='memory_entity_name_lower'),
        ),
    ]
